### ISSUE TITLE
Does't compile on Mac

### ISSUE THREAD

**Issue by grigorovich** [monsieurgustav/UE4-OSC#25] opened 2016-03-29 16:52 UTC
## 4 Errors on compile plugin.
Xcode 7.3 (Latest)

**1:**
/Plugins/OSC/Source/OSC/Private/OscSettings.cpp:62:31: error: no member named 'GetValue' in 'FIPv4Address'

**3:**
/Plugins/OSC/Source/OSC/Private/Receive/OscDispatcher.cpp:185:76: error: no member named 'GetAddress' in 'FIPv4Endpoint'

/Plugins/OSC/Source/OSC/Private/Receive/OscDispatcher.cpp:189:78: error: no member named 'GetAddress' in 'FIPv4Endpoint'

/Plugins/OSC/Source/OSC/Private/Receive/OscDispatcher.cpp:228:77: error: no member named 'GetByte' in 'FIPv4Address'

**Comment by monsieurgustav** [comment] 2016-03-30 08:28
It is probably not related to OSX, but to 4.11 preview.
Duplicate of https://github.com/monsieurgustav/UE4-OSC/issues/21, that is solved now.

**Closed by monsieurgustav** 2016-03-30 08:28 UTC
