### ISSUE TITLE
Works in editor, doesn't work in standalone

### ISSUE THREAD

**Issue by microdee** [monsieurgustav/UE4-OSC#9] opened 2015-09-12 16:33 UTC
Hello!
I'd like to use this plugin with 4.8 and it behaves pretty strangely: when i'm running my game in editor everything works fine i can receive and send osc messages and the port for receiving is taken by UE4. however when i run it standalone or packaged UE4 doesn't even take the receiving port and doesn't send messages either, it doesn't work even when the editor is closed. what can i mess up?

**Comment by monsieurgustav** [comment] 2015-09-13 01:13
Hi !
I'm away from my workstation for the next couple of weeks, so I can't test anything before that.

Remember that the settings in the editor are not necessarily the same than in the packaged game. You must press "Set as default" (up-right, AFAIK) to "bake" the settings of the project. You also can write specific INI files for packaged games (which is the point of all this).

Hope that helps...
Cheers,
Guillaume

**Comment by microdee** [comment] 2015-09-14 18:08
Tried saving as default, didn't help. No rush on this one though I found a contact who could develop a UDP string receiver really quick which works in standalone too, event- and setup-wise it works really similar to your OSC implementation. If you are curious i think i can send you the source however i can't really upload it into public i'm afraid, maybe he will do it at some point.

**Comment by secretfeature** [comment] 2016-03-14 23:31
Hi, great plugin! I am sending messages to and from Reaktor and it works great but I need to package my game to enable a multiplayer mode. I have not been able to get the plugin working when packaged. Is this the current state or should I continue debugging? Thanks for all the hard work!!

**Comment by Dannington** [comment] 2016-03-15 08:18
Ah, does it work if you use the default port?  I had to hard code the port into the source code when I packaged.  I forgot I had to do this.

**Comment by monsieurgustav** [comment] 2016-03-15 08:48
I haven't tested a packaged build recently. Something might have broken...

Did you check the logs?
At the very least, there should be "Listen to port XXXX" somewhere.

**Comment by secretfeature** [comment] 2016-03-15 09:38
Yes, in the logs it says Listen to port 8000 which is right and working in the editor.

**Comment by monsieurgustav** [comment] 2016-03-15 21:05
Windows or OSX ?

**Comment by monsieurgustav** [comment] 2016-03-15 21:39
I fail to reproduce the issue on UE4.10 and Windows.

Check that /YourProjectName/Config/DefaultEngine.ini reflects your
settings. This is the file that is updated when you click "Set as default".
A partial copy of mine:

[/Script/OSC.OscSettings]
ReceiveFrom=9000
-SendTargets=127.0.0.1:8000
-SendTargets=127.0.0.1:7000
+SendTargets=127.0.0.1:8000
+SendTargets=192.168.0.41:9000

I also add verbose logging manually, to the same file.
[Core.Log]
LogOSC=VeryVerbose


Those settings should be reflected in the package.
In the last lines of YourProjectName-WindowsNoEditor.pak (this is mostly
binary, but there is plain text too), you should see a  copy of
DefaultEngine.ini.


Finally,
\YourPackagePath\WindowsNoEditor\YourProjectName\Saved\Logs\YourProjectName.log,
should also reflect the settings.

[2016.03.15-21.26.06:400][  0]LogOSC:Display: Update settings
[2016.03.15-21.26.06:400][  0]LogOSC:Display: Stop listening
[2016.03.15-21.26.06:410][  0]LogOSC:Display: Listen to port 9000
[2016.03.15-21.26.06:410][  0]LogOSC:Display: Send targets cleared
[2016.03.15-21.26.06:410][  0]LogOSC:Display: Send target added:
127.0.0.1:8000
[2016.03.15-21.26.06:410][  0]LogOSC:Display: Send target added:
192.168.0.41:9000
[2016.03.15-21.26.06:410][  0]LogOSC:Display: Startup succeed


At home, both receive from and send to TouchOSC work.

**Comment by secretfeature** [comment] 2016-03-16 07:50
I have it working now in packaged mode. It could have either been the port I was using, Windows firewall or some other change since I was changing anything I could think of. Working really well now. For some reason it's still not working in standalone from the editor (I don't receive the Listen to port 9000 message), but not a problem. Thanks for the help, this plugin is super useful!

**Comment by monsieurgustav** [comment] 2016-03-16 18:55
I totally confused "Packaged" and "Standalone Game"!
You were totally right: the plugin did not work in "Standalone Game" (no listening).
This is fixed now!
https://github.com/monsieurgustav/UE4-OSC/commit/c073711dc68d10495ebe6d741a851672902df919

**Comment by secretfeature** [comment] 2016-03-17 23:55
Thanks!

**Comment by microdee** [comment] 2016-03-18 18:31
ah great news! thanks for reviving this!

**Closed** 2016-03-22 19:39 UTC
