### ISSUE TITLE
Incoming IP address on message receive.

### ISSUE THREAD

**Issue by Dannington** [monsieurgustav/UE4-OSC#23] opened 2016-03-09 21:28 UTC
It's not an issue!  Just a request.

I'd like to know the IP address of any given message sender.  I'm looking into using multiple iPads to control UE and i'd like to be able to setup my outgoing messages based on incoming ones at runtime.

So, I could start my game with no OSC messages coming from the engine.  Then on my iPad i can press a button which sends a message like 'I'll be iPad number 1' and UE can add a new OSC target and start transmitting back to that device.

This will save me from tediously inputting IP addresses into the engine or a config file - and also prevents me making mistakes with the ip address, which often causes an engine lock-up.

Cheers, M.Gustav!

Dan

**Comment by monsieurgustav** [comment] 2016-03-15 22:43
Hi!
https://github.com/monsieurgustav/UE4-OSC/commit/7358d0baf2d84bbc684d458310696d5a12f9ef19 does just that!
Check if it works as intended, and close the issue. :)

**Comment by Dannington** [comment] 2016-03-15 22:47
This is great! I'm not back until next week, but I'll test the plugin as
soon as I am - thanks so much for supporting this plugin so well!

Dan

**Closed** 2016-10-07 15:14 UTC
